---
title: References
output: html_document
---

1. **Snow Coverage Mapping by Learning from Sentinel-2 Satellite Multispectral Images via Machine Learning Algorithms**  
   *Remote Sensing*, 2022.  
   [https://www.mdpi.com/2072-4292/14/3/782](https://www.mdpi.com/2072-4292/14/3/782)

2. **Comparison of Three Different Random Forest Approaches to Retrieve Daily High-Resolution Snow Cover Maps from MODIS and Sentinel-2**  
   *Remote Sensing*, 2023.  
   [https://www.mdpi.com/2072-4292/15/2/343](https://www.mdpi.com/2072-4292/15/2/343)

3. **Ghosh, T. (2024). Low snow levels in the Himalaya are putting lives at risk.**  
   *Nature*.  
   [https://www.nature.com/articles/d41586-024-00123-0](https://www.nature.com/articles/d41586-024-00123-0)

4. **Almagioni, C. D., et al. (2025). Snow Cover Variability and Trends over Karakoram, Western Himalaya and Kunlun Mountains During the MODIS Era (2001–2024).**  
   *Remote Sensing*, 17(5), 914.  
   [https://www.mdpi.com/2072-4292/17/5/914](https://www.mdpi.com/2072-4292/17/5/914)

5. **Bajracharya, S. R., et al. (2022). Revealing four decades of snow cover dynamics in the Hindu Kush Himalaya.**  
   *Scientific Reports*, 12, 17575.  
   [https://www.nature.com/articles/s41598-022-21901-5](https://www.nature.com/articles/s41598-022-21901-5)

6. **Salomonson, V.V. and Appel, I., 2004. Estimating fractional snow cover from MODIS using the normalized difference snow index.**
   *Remote sensing of environment*, 89(3), pp.351-360.
   [https://www.sciencedirect.com/science/article/pii/S0034425703002864?casa_token=6sRUqSBmTp0AAAAA:LsXn1aRLTbxvRds3v4jnyNecC7fseH9PepDCkMj36ijiNqvQZqlqaEHa-EgAjEjOf_ZnyeduHA](https://www.sciencedirect.com/science/article/pii/S0034425703002864?casa_token=6sRUqSBmTp0AAAAA:LsXn1aRLTbxvRds3v4jnyNecC7fseH9PepDCkMj36ijiNqvQZqlqaEHa-EgAjEjOf_ZnyeduHA)